### ISSUE TITLE
API - integration

### ISSUE THREAD

**Issue by blake214** [blake214/Agile_project#7]
1. Figure out how we going to integrate icecat API
2. Document what requests we will need to use for the API
3. Write some 'cleaning' code to put the result into a format we can use

**Comment by hadarsharon** [comment]
I added a module under api/api.js that should include all api-related functions, and implemented functions as follows:
1. API request function to get the data
2. 'cleaning' code as mentioned in bullet #3 of the issue, that puts the result into a format we can use in the DB
